# United States - Crime Rates - 1960 - 2014

### Introduction:

This time you will create a data 

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/US_Crime_Rates/US_Crime_Rates_1960_2014.csv).

### Step 3. Assign it to a variable called crime.

In [2]:
crime = pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/04_Apply/US_Crime_Rates/US_Crime_Rates_1960_2014.csv')

In [3]:
crime.tail()

,Year,Population,Total,Violent,Property,Murder,Forcible_Rape,Robbery,Aggravated_assault,Burglary,Larceny_Theft,Vehicle_Theft
50,2010,309330219,10363873,1251248,9112625,14772,85593,369089,781844,2168457,6204601,739565
51,2011,311587816,10258774,1206031,9052743,14661,84175,354772,752423,2185140,6151095,716508
52,2012,313873685,10219059,1217067,9001992,14866,85141,355051,762009,2109932,6168874,723186
53,2013,316497531,9850445,1199684,8650761,14319,82109,345095,726575,1931835,6018632,700294
54,2014,318857056,9475816,1197987,8277829,14249,84041,325802,741291,1729806,5858496,689527

### Step 4. What is the type of the columns?

In [4]:
crime.dtypes

Year                  int64
Population            int64
Total                 int64
Violent               int64
Property              int64
Murder                int64
Forcible_Rape         int64
Robbery               int64
Aggravated_assault    int64
Burglary              int64
Larceny_Theft         int64
Vehicle_Theft         int64
dtype: object

##### Have you noticed that the type of Year is int64. But pandas has a different type to work with Time Series. Let's see it now.

### Step 5. Convert the type of the column Year to datetime64

In [5]:
crime['Year'] = pd.to_datetime(crime['Year'], format='%Y')

### Step 6. Set the Year column as the index of the dataframe

In [6]:
crime = crime.set_index(['Year'], drop = True)

In [7]:
crime.dtypes

Population            int64
Total                 int64
Violent               int64
Property              int64
Murder                int64
Forcible_Rape         int64
Robbery               int64
Aggravated_assault    int64
Burglary              int64
Larceny_Theft         int64
Vehicle_Theft         int64
dtype: object

In [8]:
crime.tail()

,Population,Total,Violent,Property,Murder,Forcible_Rape,Robbery,Aggravated_assault,Burglary,Larceny_Theft,Vehicle_Theft
Year,,,,,,,,,,,
2010-01-01,309330219,10363873,1251248,9112625,14772,85593,369089,781844,2168457,6204601,739565
2011-01-01,311587816,10258774,1206031,9052743,14661,84175,354772,752423,2185140,6151095,716508
2012-01-01,313873685,10219059,1217067,9001992,14866,85141,355051,762009,2109932,6168874,723186
2013-01-01,316497531,9850445,1199684,8650761,14319,82109,345095,726575,1931835,6018632,700294
2014-01-01,318857056,9475816,1197987,8277829,14249,84041,325802,741291,1729806,5858496,689527

### Step 7. Delete the Total column

In [9]:
crime = crime.drop(labels='Total', axis=1)
crime.tail()

,Population,Violent,Property,Murder,Forcible_Rape,Robbery,Aggravated_assault,Burglary,Larceny_Theft,Vehicle_Theft
Year,,,,,,,,,,
2010-01-01,309330219,1251248,9112625,14772,85593,369089,781844,2168457,6204601,739565
2011-01-01,311587816,1206031,9052743,14661,84175,354772,752423,2185140,6151095,716508
2012-01-01,313873685,1217067,9001992,14866,85141,355051,762009,2109932,6168874,723186
2013-01-01,316497531,1199684,8650761,14319,82109,345095,726575,1931835,6018632,700294
2014-01-01,318857056,1197987,8277829,14249,84041,325802,741291,1729806,5858496,689527

### Step 8. Group the year by decades and sum the values

#### Pay attention to the Population column number, summing this column is a mistake

In [10]:
# Uses resample to sum each decade
crimes = crime.resample('10YS').sum()

# Resample to get the max value for the "Population" column
population = crime['Population'].resample('10YS').max()

crimes.Population = population

crimes

,Population,Violent,Property,Murder,Forcible_Rape,Robbery,Aggravated_assault,Burglary,Larceny_Theft,Vehicle_Theft
Year,,,,,,,,,,
1960-01-01,201385000,4134930,45160900,106180,236720,1633510,2158520,13321100,26547700,5292100
1970-01-01,220099000,9607930,91383800,192230,554570,4159020,4702120,28486000,53157800,9739900
1980-01-01,248239000,14074328,117048900,206439,865639,5383109,7619130,33073494,72040253,11935411
1990-01-01,272690813,17527048,119053499,211664,998827,5748930,10568963,26750015,77679366,14624418
2000-01-01,307006550,13968056,100944369,163068,922499,4230366,8652124,21565176,67970291,11412834
2010-01-01,318857056,6072017,44095950,72867,421059,1749809,3764142,10125170,30401698,3569080

### Step 9. What is the most dangerous decade to live in the US?

In [15]:
crimes.idxmax(0)

Population           2010-01-01
Violent              1990-01-01
Property             1990-01-01
Murder               1990-01-01
Forcible_Rape        1990-01-01
Robbery              1990-01-01
Aggravated_assault   1990-01-01
Burglary             1980-01-01
Larceny_Theft        1990-01-01
Vehicle_Theft        1990-01-01
dtype: datetime64[ns]