# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [2]:
chipo = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv', sep='\t')

In [3]:
chipo.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

### Step 4. How many products cost more than $10.00?

In [7]:
# create a new Series cleaning the item_price column to transform it to a float
prices = [float(value[1 : -1]) for value in chipo.item_price]

# reassign the column with the cleaned prices
num_chipo = chipo.copy()
num_chipo.item_price = prices

# Get the items with item_price > 10.0
num_chipo.query('item_price > 10').item_name.nunique()

31

### Step 5. What is the price of each item?
###### print a data frame with only two columns item_name and item_price

In [8]:
num_chipo[['item_name', 'item_price']].drop_duplicates()

                                  item_name  item_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl       16.98
...                                     ...         ...
4237                    Chips and Guacamole        8.50
4354                       Steak Soft Tacos       18.50
4489                    Chips and Guacamole       17.80
4509                                  Chips        1.99
4510                          Barbacoa Bowl       11.49

[209 rows x 2 columns]

### Step 6. Sort by the name of the item

In [9]:
num_chipo.sort_values(by=['item_name'])

,order_id,quantity,item_name,choice_description,item_price
3389,1360,2,6 Pack Soft Drink,[Diet Coke],12.98
341,148,1,6 Pack Soft Drink,[Diet Coke],6.49
1849,749,1,6 Pack Soft Drink,[Coke],6.49
1860,754,1,6 Pack Soft Drink,[Diet Coke],6.49
2713,1076,1,6 Pack Soft Drink,[Coke],6.49
...,...,...,...,...,...
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49

### Step 7. What was the quantity of the most expensive item ordered?

In [13]:
# Find most expensive item_name.
most_expensive = num_chipo.query('item_price == item_price.max()')
most_expensive

,order_id,quantity,item_name,choice_description,item_price
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,44.25

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [24]:
chipo_salad = chipo[chipo.item_name == "Veggie Salad Bowl"]

#chipo_salad
len(chipo_salad)

18

### Step 9. How many times did someone order more than one Canned Soda?

In [27]:
mo_soda = chipo[(chipo.item_name == "Canned Soda") & (chipo.quantity > 1)]
# mo_soda
len(mo_soda)

20